/** Catálogo de eventos (punto 57). Sin PII: sólo userId + propiedades de producto. */
export const ANALYTICS_EVENTS = [
  "signup_started",
  "signup_completed",
  "onboarding_started",
  "onboarding_completed",
  "profile_updated",
  "wardrobe_item_add_started",
  "wardrobe_item_added",
  "wardrobe_item_deleted",
  "wardrobe_category_completed",
  "wardrobe_progress_changed",
  "outfit_generation_started",
  "outfit_generated",
  "alternate_outfit_requested",
  "outfit_selected",
  "outfit_used",
  "outfit_rejected",
  "outfit_feedback_submitted",
  "points_earned",
  "streak_updated",
  "mission_started",
  "mission_completed",
  "reward_viewed",
  "reward_redeemed",
  "referral_created",
  "referral_activated",
  "product_viewed",
  "product_clicked",
  "purchase_completed",
  "review_submitted",
] as const;

export type AnalyticsEventName = (typeof ANALYTICS_EVENTS)[number];
